---
language: go
go:
  - '1.15'

env:
  - GO111MODULE=on

stages:
- build
- name: release
  if: tag =~ ^v

jobs:
  include:
  - stage: build
    name: lint & test & build
    script: make all
  - stage: release
    name: publish release artifacts
    script:
      - make release
      - .travis/publisher.sh
