---
# Handles labelling of PR's.
name: Pull Request Labeler
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://docker.io/ilyam8/periodic-pr-labeler:v0.1.1
        if: github.repository == 'netdata/go.d.plugin'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LABEL_MAPPINGS_FILE: .github/labeler.yml
